version: "3.0"
services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    volumes:
      - . :/go/src/coding-prep/docker-go-server
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
